### PR TITLE
generate_emu_config overhaul (a lot of bugfixes, improvements, new features, new file structure, new helper tools)

### PR DESCRIPTION
**Pull request by alex47exe**
* **[alex47exe]** major overhaul of **generate_emu_config** - custom configs, proper ini parsing, better logging and error handling, helper tools:

  * add `-def1` ... `-def5` arguments, which can be used to generate your preferred custom config  
    if no `-def` argument is provided, `-def1` will be used by default, to automatically copy from the following folders: 
    * `.\_DEFAULT\0` ............... essential emu files, like latest GSE dlls (*steam_api.dll* and *steam_api64.dll*)
    * `.\_DEFAULT\1` ............... other GSE files and folders, including default ini files
    * `.\_DEFAULT\<appid>` ... other GSE files and folders, but only for the current `<appid>`, if the folder exists 
  * (Windows only) add some useful helper tools, written in *AutoIt3*:

    * **gse_acw_helper.exe** - add the required achievements schema db files for *Achievement Watcher*, if  .\steam_misc\extra_acw\extra_acw.zip file exists (if generated by `generate_emu_config.exe -acw <appid>`)
    * **gse_debug_switch.exe** - automatically switch between release and debug versions of the emulator, if *steam_api.7z* / *steam_api64.7z* file exists (or *steamclient.7z* / *steamclient64.7z*, if you use the steamclient version)
      paths to release and debug files inside 7z, can be customized in .\steam_misc\tools\au3\scripts\gse_debug_switch.ini
    * **gse_generate_interfaces.exe** - simple x64-x86 launcher for *generate_interfaces.exe*
      it also writes all found steam interfaces to CODEX *steam_emu.ini* (if generated by `generate_emu_config -cdx <appid>`)  
      make sure to name your original dll to one of these formats, so it can automatically find its interfaces:
      * `valve_api.dll / valve_api64.dll`
      * `steam_api.dll.bak / steam_api64.dll.bak` or `steam_api.dll.org / steam_api64.dll.org`
      * `steam_api.bak / steam_api64.bak` or `steam_api.org / steam_api64.org`
      * `steam_api_orig.dll / steam_api64_orig.dll` or `steam_api_legit.dll / steam_api64_legit.dll`
    * **gse_lobby_connect.exe** - simple x64-x86 launcher for *lobby_connect.exe*
  * new folder structure, compatible with current and future helper tools --- default arguments are `-acw -cdx -clr <appid>`  
    NEVER delete `.\steam_misc\app_backup`, `.\steam_misc\app_info`, `.\steam_misc\tools` and `.\steam_settings` folders  
    MIGHT need `.\steam_misc\extra_acw` and `.\steam_misc\extra_cdx` for compatibility with Achievement Watcher and CODEX 
  * add `-scx` argument to automatically download images / videos for trading cards, backgrounds, badges, emoticons and other tradable items 
    unfortunately I couldn't find any direct steam api method to download the files, so I had to write a rudimentary web scrapper to extract the download links from a third-party website, hence the *scx_gen.py* script might need updating in the future if the website design changes
  * download screenshots and videos:

    * download thumbnails for both screenshots and videos, and compress them to `.zip` files
    * screenshots and videos are now numbered from first to last published, as in the Steam store page
    * add `-vids_low` / `-vids_max` arguments to download all videos, in low and / or high quality
  * create / update .\\*top_owners_ids.txt* when .\\*top_owners_ids.html* is present
  * generate controller action sets txt files for all found controller vdf configs, and zip them inside .\steam_misc\app_backup\app_backup.zip  
    by default, the emu supports only `xboxone` and `xbox360` controller configs, though if the're are any issues with the default supported controller action sets inside .\steam_settings\controller folder, you could try to unpack and overwrite action sets for other unsupported controller configs
  * (Windows only) add *AdvancedRun* launchers (cmd console + silent) for `.bat` files and `.py` scripts
* **[alex47exe]** major overhaul of **migrate_gse** - uses the same `.\_DEFAULT\0` and `.\_DEFAULT\1` folder structure for default configs  
  it can convert old `.txt` format to `.ini` format, minus *branches.json*, which would require using *top_owners_ids.txt* and some login code from **generate_emu_config**, which should actually be used to properly generate the config files, instead of converting from the old `.txt` format
* **[alex47exe]** *generate_interfaces.exe* - find all Steam Interfaces instead of only old ones   
  the emu will ignore the ones it doesn't require, while we'll have the complete list to write it to CODEX *steam_emu.ini*
* **[alex47exe]** *lobby_connect.exe* - improve cmd console text alignment
* **[alex47exe]** `mods_img` instead of `mod_images` (better folder consistency), better example for `mods_img`, minor tweaks to `.ini` and `.md` files

### CODE REVIEW

**Comment by alex47exe** [comment]
Not sure why it takes so long to build the experimental debug api here. Mine was done in less than 3 minutes: 
[https://github.com/alex47exe/gse_fork/actions/runs/10154145974/job/28078796689](https://github.com/alex47exe/gse_fork/actions/runs/10154145974/job/28078796689)
Maybe you could try to re-run checks again. Or try a merge to a different branch, and run 'Prepare release' action manually.

**Comment by Detanup01** [comment]
Seems like github issue (I could merge without actually waiting to finish all builds btw) will reopen and probably request some changes (mainly in the ini what should be default) not today but tomorrow.

**Comment by alex47exe** [comment]
Sure, any suggestions are welcome! I just copy pasted the custom ini files included in default configuration for generate_emu_config, but forgot to restore the original values for the example ini files. 
I guess the whole update should've been split in more commits, but it has been cooking offline for the past 3 weeks or so, without using git to properly commit and document all changes and iterations.

**Comment by Detanup01** [comment]
:D no worries

**Comment by Detanup01** [comment]
tools/generate_emu_config/generate_emu_config.py_ini.exe
tools/generate_emu_config/generate_emu_config.*.exe
why?
Also the default plus zips are probably not needed we can let users place steamapi dlls there.
also 7z exists inside the third-party folder

**Comment by alex47exe** [comment]
___ The exe files are basically just stripped down (no interface) AdvancedRun executables plus their required cfg (commented / documented by me), basically a better method to run various scripts and apps with parameters (including python), with or without interface if required (useful when you need to run an app or script silently -no cmd window flash even-, e.g. when we might need to integrate generate_emu_config into any other automated tool). To be honest, I'm surprised Microsoft doesn't include AdvancedRun by default in an app bundle (and properly integrated with context menu), like they do with Sysinternals Suite or PowerToys, 'cause I really find it the best method to easily run apps and scripts with parameters. Anyway, about those exes:
- *py_ini.exe - only required to run once, installs required python packages to allow running python generate_emu_config.py directly, useful during development
- *py_anon.exe - runs generate_emu_config.py script (needs python installed) in anonymous mode, doesn't fetch achievements, stats and maybe some other things too
- *py_user.exe - runs generate_emu_config.py script (needs python installed) with your own user account and password, to fetch the complete configuration for the game
- *exe_anon.exe (in post_build folder) - runs compiled generate_emu_config in anonymous mode, no need to have an *exe_ini.exe, as all required packages are included in the compiled exe
- *exe_user.exe (in post_build folder) - runs compiled generate_emu_config with your own user account and password, no need to have an *exe_ini.exe, as all required packages are included in the compiled exe

___ If you are referring to steam_api.7z and steam_api64.7z, they include both release and debug versions of the emulator, needed for gse_debug_switch.exe - I think one double-click to run it is a much superior method of changing between release and debug versions when needed, instead of having to manually backup and copy paste them

___ 7za.exe is currently required by gse_debug_switch.exe and gse_acw_helper.exe, and might be required by future tools I currently have some ideas for. I could've used an AutoIt3 UDF script (user defined functions) for zip compression / decompression, but I prefer 7z. Though I used zip compression in generate_emu_config.py for the app_backup folder, screenshots and trailers thumbnails, and parsed download links for SCX scrapper. What I could do is intergrate 7za.exe in a3x script, and unpack it when the script runs, but that would mean every other future a3x script would have to integrate it as well, in the end taking more hdd space than the current method.

**Comment by Detanup01** [comment]
For 7z:
if you pull eveything from here and even the submodules, you find out the 
third-party/deps/linux
third-party/deps/windows
already contains your 7zip.


For the steam apis 7z:
You cannot make push to update because it will always be behind it.

Also probably could make a github action for building the tools rather than having the exe inside there (which I dont like it.)

**Comment by alex47exe** [comment]
Regarding steam apis 7z, the way I handled them was to manually build the emu on windows, then manually create the steam apis 7z containing both release and debug versions, then push the whole github folder using GitExtensions. Sure, I would love to automate this, but unfortunately I am not experienced with github actions. I guess it would basically mean that the generate_emu_config build would have to be delayed after the emu build, so that the compiled steam apis can be copied and archived to steam apis 7z first. 
Same for the already included 7za.exe (though I am not sure why it's an issue) and compiled a3x scripts, both could be achieved automatically through some github actions and / or bat files. So we would need a github action (or modifications to one) to automatically install latest 7zip and AutoIt3, then add 7za.exe to the correct folder, and also build the au3 scripts with Aut2Exe.exe, as explained here: [https://www.autoitscript.com/autoit3/docs/intro/compiler.htm](https://www.autoitscript.com/autoit3/docs/intro/compiler.htm)
Finally, after all these actions complete successfully, we can build the generate_emu_config executable.

**Comment by rcyggdra** [comment]
> Seems like github issue (I could merge without actually waiting to finish all builds btw) will reopen and probably request some changes (mainly in the ini what should be default) not today but tomorrow.

For familiar people, this PR appears bloated. 
If you want to merge this PR, I hope it will be on the new branch instead of replacing the existing one.

**Comment by alex47exe** [comment]
> For familiar people, this PR appears bloated. If you want to merge this PR, I hope it will be on the new branch instead of replacing the existing one.
 
What do you mean 'bloated'? Sure, maybe it should have been split in more commits, as I said above, but other than that, it only improves generate_config_emu and migrate_gse (though currently it can't generate branches.json, so I don't recommend using it - just regenerate the entire config instead), adds much needed helper tools for automation of various tasks, and corrects spelling mistakes / adds minor changes to wording and punctuation to some readme files. That's literally all it does. It's not 'bloated', it's improved - you just haven't tested it thoroughly to understand it.

**Comment by alex47exe** [comment]
Just reopened it to be able to fix conflicts with upstream fork, so I can correctly merge the latest changes into my own

**Comment by Detanup01** [comment]
If you edit the request to be a draft I would be thankfull

**Comment by alex47exe** [comment]
Sure thing. Haven't really had the time lately to fully and correctly automate all the necessary building and packaging of extra tools I added. There's still some new useful things I'll add into the generate_emu_config tool, like automatically finding and creating shortcuts to the configuration and savegame folders based on data already present in app_details.json (which is part of the reason I decided to include by default some extra json files based on app_details.json) and also scrapped info from PCGamingWiki page for each game - the page link can be obtained automatically through https://www.pcgamingwiki.com/api/appid.php?appid=391220 (example for 'Rise of the Tomb Raider)
I hope that converting the pull request to draft will still let me correct the future differences to be able to correctly merge all future updates to your fork into mine. If it does, thanks, as I was keeping the pull request open for that reason.

**Comment by God-damnit-all** [comment]
The changes make `-rel` (formerly `-reldir`) not work correctly, at least not with the compiled exe.
```
Traceback (most recent call last):
  File "generate_emu_config.py", line 1348, in <module>
  File "generate_emu_config.py", line 835, in main
  File "shutil.py", line 598, in copytree
FileNotFoundError: [WinError 3] The system cannot find the path specified: '_DEFAULT\\0'
``

**Comment by alex47exe** [comment]
Just tested with a few app ids and `-rel` doesn't error out for me, though it also doesn't make a difference in the output files. To be honest, I haven't really used that (or `-reldir`, how it was named before), as the generator uses a totally different folder structure in order to support all improved features and helper tools. I was mostly focused on improving and fixing the generator as far as I could...
Not sure what it was actually supposed to do, as it's not so well explained... 
- generate the entire config in same folder as the generator?
- expect input files... what input files? the generator doesn't need any file or folder parameter.
- all the files generated (aka the complete game configuration for steam_api dll folder) are already relative to the generator's working folder

Since it seems to be useless for the current version, I'll probably remove it, unless someone can say what it's needed for.

**Comment by God-damnit-all** [comment]
> Just tested with a few app ids and `-rel` doesn't error out for me, though it also doesn't make a difference in the output files. To be honest, I haven't really used that (or `-reldir`, how it was named before), as the generator uses a totally different folder structure in order to support all improved features and helper tools. I was mostly focused on improving and fixing the generator as far as I could... Not sure what it was actually supposed to do, as it's not so well explained...
> 
> * generate the entire config in same folder as the generator?
> * expect input files... what input files? the generator doesn't need any file or folder parameter.
> * all the files generated (aka the complete game configuration for steam_api dll folder) are already relative to the generator's working folder
> 
> Since it seems to be useless for the current version, I'll probably remove it, unless someone can say what it's needed for.

Please don't do that, I use it. I'm the one who requested it to be added in the first place in the previous iteration of gbe_fork. It makes it so the working directory isn't based on the binary's directory. So try to run it from one directory up, e.g. `./generate_emu_config/generate_emu_config`

**Comment by alex47exe** [comment]
> Please don't do that, I use it. I'm the one who requested it to be added in the first place in the previous iteration of gbe_fork. It makes it so the working directory isn't based on the binary's directory. So try to run it from one directory up, e.g. `./generate_emu_config/generate_emu_config`

I see now... let me know if I understand what you're trying to do:
- run the generator through a bat or external tool from another folder, and output the complete config to it instead of next to generate_emu_config.exe 
- do you want to still output it in a _OUTPUT\<appid> folder or directly next to the new bat or external tool calling the generator?
- do you want to still copy the _DEFAULT\0 and _DEFAULT\1 (or 2-5) template configs from the generator folder or from the new one, where your bat or external tool is located, possibly overriding the previous _DEFAULT template configs?

The script will need a few modifications to properly use `-rel` argument

**Comment by God-damnit-all** [comment]
> > Please don't do that, I use it. I'm the one who requested it to be added in the first place in the previous iteration of gbe_fork. It makes it so the working directory isn't based on the binary's directory. So try to run it from one directory up, e.g. `./generate_emu_config/generate_emu_config`
> 
> I see now... let me know if I understand what you're trying to do:
> 
> * run the generator through a bat or external tool from another folder, and output the complete config to it instead of next to generate_emu_config.exe
> * do you want to still output it in a _OUTPUT<appid> folder or directly next to the new bat or external tool calling the generator?
> * do you want to still copy the _DEFAULT\0 and _DEFAULT\1 (or 2-5) template configs from the generator folder or from the new one, where your bat or external tool is located, possibly overriding the previous _DEFAULT template configs?
> 
> The script will need a few modifications to properly use `-rel` argument

Basically I have everything that the generate_emu_confg archive comes with independently existing in another folder for ease of upgrading, while my configs and outputs are elsewhere because I'm calling all that from another folder.

So yes to the first two questions. Indifferent to the last one.

**Comment by alex47exe** [comment]
@God-damnit-all, take a look at the latest release and let me know if it works correctly with the new `-rel_out` and `-rel_raw` arguments
[https://github.com/alex47exe/gse_fork/releases/tag/2024_10_21](https://github.com/alex47exe/gse_fork/releases/tag/2024_10_21)

**Comment by God-damnit-all** [comment]
@alex47exe They work, but I'd also used `-reldir` to make it use the working directory's my_login.txt file.

**Comment by alex47exe** [comment]
[https://github.com/alex47exe/gse_fork/releases/tag/2024_11_12](https://github.com/alex47exe/gse_fork/releases/tag/2024_11_12)

* add latest changes from Detanup01's [gbe_fork](https://github.com/Detanup01/gbe_fork) up to this [commit](https://github.com/Detanup01/gbe_fork/tree/a1462a9eca4908f7b6ec3925d7ccd2842a7e22fe)
   * add 'appid_finder' mode for 'generate_emu_config':
   * runs with only '-find' and '-rel_raw' parameters, automatically finds appid by searching game folder name on google
   * then it starts a simple external interface (written in AutoIt3) to check if it found the correct appid
   * if it hasn't found the correct appid you can browse left or right to see other possible matches, or write the game name under the game image, then press 'NO, RETRY' - you can do this as many thimes as you like...
   * once you found the correct appid, just press 'YES, CONTINUE' and generate_emu_config will start without asking you for appid
   * for now you can test 'appid_finder' byt running 'appid_finder.bat' - it will later be properly integrated to be able to do it all in one go, though it's already possible if you copy the contents of 'appid_finder' folder to your game folder, then edit the two bat files with the correct generate_emu_config location

Building it on github will fail, unless you also modify the github workflows as those on my fork, to only start generate_emu_config build after emulator build completes.

**Comment by God-damnit-all** [comment]
What happened with this PR?

**Comment by alex47exe** [comment]
> What happened with this PR?

Nothing happened. Basically, even though it contains countless improvements and fixes for generate_emu_config, Detanup01 was skeptical about it using some extra executables (AdvancedRun -reshacked, no icon, no gui- with its cfg file properly documented by me, and AutoIt to run the compiled a3x scripts - source au3 files included for peace of mind) for various helper tools, so it didn't get merged. Long story short, if you want Detanup01's gbe_fork with this PR, use my gse_fork, which is up to date with Detanup01's, as far as emulator goes, plus this PR.

**Comment by Detanup01** [comment]
Yup, exe's and non source related stuff shouldn't be in the repo. 
That's why I want to make repo for generate_emu_config. Good to have but people already use other solution, plus high % of time it doesn't required.
Plus controller stuff, some app doesn't work, nyeh. Overall I said back then when the gen emu was broken to migrate over steamkit since updated rather than the python one.

**Comment by alex47exe** [comment]
Seriously, have you even tried the one on your fork with some strange scenarios, like batch generating and providing it with some invalid appids, even text strings, or appids of steam events or steam tools? Wanna bet which one does properly skip the invalid ones (and/or generates whatever it can) without failing completely for all of them at the first invalid one? Or even providing it with the wrong username and password?
Have you even noticed that some random dlc entries add double quotes, when they are nowhere to be found on steamdb? Or that screenshots downloaded with yours are randomly named, while mine are named in the same order as on steam page? Or that you can't download all videos with yours, you can't choose video quality to download them? Or that you can't properly generate the codex/rune ini, with all correct interface versions with yours? Or that you can't automatically download assets for trading cards, badges, backgrounds, emoticons, etc? Or that yours doesn't properly generate the complete (default or not) ini files, since it does't do that by using template folders for generation, but by hardcoding -which is always a bad idea- the entries for the ini files? Or that you can't even dream to use yours to automatically crack any steam game, since it doesn't include an appid_finder and/or is not coded to interact with one? Or that its text output is minimal and inconsistent? And countless other fixes...
Because it really doesn't seem that you tested it as thoroughly as I did... So, no... as far as I know, there's no other solution that takes into account all these scenarios. The ultimate goal with my improvements and fixes for generate_emu_config is to run automatically, even silently if needed and properly crack a game based just on its folder name, hell... properly crack one hundred games at once, why not. Haven't really had the time lately, but the only things missing to do that is adding some features like automatic steamless patching, backup of original steam_api dll, game exe and other files (if needed), and a simple interface similar to the included appid_finder (or even merged with it). But, hey... it's your choice to keep using the highly broken and inconsistent one on your fork! I'll continue improving it on mine anyway, but having two forks just adds for a lot of confusion for some people, when both use the exact same emulator... a lot of useless questions and issues could be avoided on a certain forum...

**Comment by God-damnit-all** [comment]
So uh, why not just use [pyautoit](https://pypi.org/project/PyAutoIt/) for the AutoIt scripts and come up with a solution for running certain things other than AdvancedRun?

**Comment by alex47exe** [comment]
pyautoit is very limited, doesn't support more advanced au3 scripts... 
advancedrun is used to hide starting cmd console when running bat scripts... don't know any other simple solution for that, though it can do much more than that if you look in the cfg files

To be honest, I don't see the issue having a few small executables that run the helper scripts and bat files properly. Trust me it would be worse if I compiled the au3 scripts to exe, as they usually get a lot of false positives - even a completely empty script might be seen as false positive by some avs. I have a working solution for that which involves compiling them in a different way, basically wrapping the compiled a3x script and autoit3 exe inside a silent automated inno setup, but the executables will take about 10MB or each, so it's not worth it for the current purpose - better use the small advancedrun plus its config to run each a3x script

**Comment by Edremon** [comment]
The solution is to improve the existing script rather than what you are doing. I'm glad that this PR has not been merged; the quality is atrocious. Having random binaries and compiled builds in your repo is horrible. Instead of contributing useful changes to this repo, you have only made a mega PR with tons of poor changes.

**Comment by alex47exe** [comment]
> The solution is to improve the existing script rather than what you are doing. I'm glad that this PR has not been merged; the quality is atrocious. Having random binaries and compiled builds in your repo is horrible. Instead of contributing useful changes to this repo, you have only made a mega PR with tons of poor changes.

Bro, you're plain wrong, you have no idea what you're talking about, the script has countless improvements and fixes. The helper tools are just extra and designed to work with it, since some steps are required to run only after it copies the generated files to game folder.  The other 'tons of poor changes' include minor tweaks to readme and config files, and a few supporting bat scripts to properly build the release for generate_emu_config. This just shows you haven't been bothered to even download, and look into it, not to mention test it with some of the scenarios I mentioned above. You haven't even properly test Detanup01's version, none of you have, otherwise the issues would have started to pile up. I appreciate all you guys' contributions to the emulator side, I wouldn't even know where to begin to modify it on my own, but when talking about generate_emu_config, I'm confident enough with both python and autoit to know what I'm doing. Seriously, if you had bothered to look, you would've seen that only the main script has about 1700 lines added/modified, and the whole generate_emu_config, has more than 3000, not even including some external github repo, used for the appid_finder part of it, which is integrated into, but works with an external au3 interface. I find it laughable that you guys are bothered by some small proven safe exes and scripts and can't consider all possible approaches to fixing and improving a program --- just shows lack of open mindness, limited thinking regarding this pr, and a bit of arrogance to be honest, when all of us here are trying our best to fix and improve various things for this project. And no, there are no compiled builds in the repo, the compiled dlls are added automatically to generate_emu_config when running the release action. Let me guess... you had no idea about this too. Let it be clear, I don't care now if it's gonna get merged or not, but you can bet on whatever you want that this is the best version of generate_emu_config!

**Comment by God-damnit-all** [comment]
> The solution is to improve the existing script rather than what you are doing. I'm glad that this PR has not been merged; the quality is atrocious. Having random binaries and compiled builds in your repo is horrible. Instead of contributing useful changes to this repo, you have only made a mega PR with tons of poor changes.

I think that's a very unfair assessment. @alex47exe has put a lot of work into this and it's very thorough.

That said, I do feel like it's a little much. When I tried it out it generated much more than what was necessary. And I think @Detanup01's complaints about the use of external tools are legitimate.

That said, unless there's been communication happening outside of this PR, it does seem like @alex47exe hasn't been receiving very much feedback despite continuously putting in effort.

Surely there can be compromises rather than a blanket dismissal.

> advancedrun is used to hide starting cmd console when running bat scripts... don't know any other simple solution for that

That's easily accomplished in a multitude of ways. When launching from Python, simply use the CREATE_NO_WINDOW flag with subprocess. When launching from another batch script, you could use something like [Invisible.vbs](https://ss64.com/vb/run.html#:~:text=Invisible.vbs) or something like:

```batch
::Setting the path as an env variable is done so it can be given to the Start-Process command directly instead of potentially running into quote-escaping issues.
SET "_path_to_other_batch=PATHGOESHERE"
powershell -NoProfile -Command "Start-Process cmd -ArgumentList '/c', $env:_path_to_other_batch -WindowStyle Hidden"
::Shortened:
powershell -NoP SaPs cmd -Args '/c', $env:_path_to_other_batch -WindowStyle 1
::Shorter still (non-standard aliasing):
powershell/NoP SaPs cmd -A '/c',$env:_path_to_other_batch -W 1
```

> pyautoit is very limited, doesn't support more advanced au3 scripts...

Why is AutoIt even needed in the first place here? What's it doing that Python can't? And can't the au3 scripts be simplified so it's made compatible?

And why is pyautoit limited? I didn't see any indication of that.

**Comment by God-damnit-all** [comment]
Oh, I see, pyautoit won't run a full AutoIt script, just individual functions.

But yeah, what's it needed for anyway?

**Comment by alex47exe** [comment]
> Oh, I see, pyautoit won't run a full AutoIt script, just individual functions.
> 
> But yeah, what's it needed for anyway?

What do you mean? Autoit is the interpreter exe needed to run au3 (source) or a3x (compiled) scripts for the helper tools. And yeah, some of the helper tools could be completely integrated and written in python or consolidated into a single app with a simple gui. I'll look into that once I add the changes to allow it to automatically crack any games based just on the folder name (though it can already do that with the included appid_finder example) It will basically be a wrapper tool, that will automatically download the latest versions of generate_emu_config (the one on my fork, obviously) and steamless (to check and remove steam stub drm), properly create backups of replaced files and possibly create the complete 7z archive with all the necessary cracked files.

Also, running powershell already creates a console window, even if it's visible only for a fraction of a second, so this completely misses the point. Nirsoft's AdvancedRun is a launcher that can do that and also so much more, just by having a properly configured cfg file next to it, named same as exe. Did my best to properly document the cfg files, so that its user interface could be reshacked out of it, just to prevent starting the exe without the cfg file and generally messing things up.

**Comment by God-damnit-all** [comment]
> What do you mean? Autoit is the interpreter exe needed to run au3 (source) or a3x (compiled) scripts for the helper tools.

I mean what functionality is AutoIt currently providing you that Python either can't do or you don't know how to do in Python?

> Also, running powershell already creates a console window, even if it's visible only for a fraction of a second, so this completely misses the point.

I know about this issue which is why I said _running from a batch script_. It's why I led with the "CREATE_NO_WINDOW" flag from subprocess, which should work for you.

**Comment by alex47exe** [comment]
As I said, I could do it in python, but some steps are required to run after the files have been properly placed inside game folder. E.g. generating steam_interfaces using gse_generate_interfaces.exe (advancedrun) which runs generate_interfaces.a3x (autoit3), will also properly write steam interfaces for codex and rune ini files if they exist in steam_misc\extra_crk\codex and rune folders. Same with gse_acw_helper which helps with automatically adding the game to achievement watcher and automatically unpacking schema files from steam_misc\extra_acw\extra_acw.zip

Sure, as I said, the helper scripts could be eventually integrated into generate_emu_config once it will run completely automated, but that would only work when using -rel_out or -rel_dir parameter (most likely I will settle for -rel_out, to avoid overwriting any files in the main game folder, before actually backing them up). If you will not use that parameter, the script will not know the location of the game folder, and the helper tools will have to be standalone as they are now - and between python standalone and autoit standalone, it's better to choose autoit which takes a lot less space than compiled python.

As for no window bat scripts, they can already run from AdvancedRun. They can even be written as multi-line commands in the cfg file. To be honest, I'm surprised a similar tool is not integrated into Windows, as its very handy to have. Sure, create_no_window flag would work too, but provided you hardcode the bat call into another exe, and as I mentioned before, I don't like hardcoding things. Not when similar result can be achieved with and exe less than 100kb with its config file, plus you can customize the exe, add your own icon and version info if you wish, which I find more elegant than relying on harcoding or other external scripts.

**Comment by Edremon** [comment]
> That said, unless there's been communication happening outside of this PR, it does seem like @alex47exe hasn't been receiving very much feedback despite continuously putting in effort.

I hadn't posted anything because my feedback is mostly negative. I only wanted to share my disagreement if some people were interested in merging it. The thing is that the whole direction is wrong. All the AutoIt, binaries, and Windows-specific elements need to be purged. I don't even want to read the diff and cherry-pick useful changes because it's completely tainted with a lot of stuff that I and any competent developer don't want to touch. Additionally, in his communication and decision-making, it's hard to distinguish between good fixes/features and useless/bad features that only alex wants or uses.

Even the recent posts are full of red flags, indicating that it's still going in an awful direction:  "Autoit", "interpreter exe", "au3", "a3x", "gui", "powershell", "Nirsoft's AdvancedRun".

If improvements need to be made to generate the emu config, it would be better to define the problems with the current script and either open an issue or a PR to fix them. Honestly, I don't think I have any problem with it, but I was the one who made a similar script in the first place, which Mr. Goldberg modified and added to his repo.

**Comment by alex47exe** [comment]
> If improvements need to be made to generate the emu config, it would be better to define the problems with the current script and either open an issue or a PR to fix them. Honestly, I don't think I have any problem with it, but I was the one who made a similar script in the first place, which Mr. Goldberg modified and added to his repo.

Feel free to thoroughly test out generate_emu_config and create issues and fixes. You'll probably still be behind mine in terms of fixes, features, design and functionality after a few months. :) 
As for the other nitpicking complaints, they're laughable... btw, python code, even compiled python code still runs through an interpreter exe. Did you know that? Make sure to cross it off the list of red flags then.

**Comment by God-damnit-all** [comment]
> > That said, unless there's been communication happening outside of this PR, it does seem like @alex47exe hasn't been receiving very much feedback despite continuously putting in effort.
> 
> I hadn't posted anything because my feedback is mostly negative. I only wanted to share my disagreement if some people were interested in merging it. The thing is that the whole direction is wrong. All the AutoIt, binaries, and Windows-specific elements need to be purged. I don't even want to read the diff and cherry-pick useful changes because it's completely tainted with a lot of stuff that I and any competent developer don't want to touch. Additionally, in his communication and decision-making, it's hard to distinguish between good fixes/features and useless/bad features that only alex wants or uses.
> 
> Even the recent posts are full of red flags, indicating that it's still going in an awful direction: "Autoit", "interpreter exe", "au3", "a3x", "gui", "powershell", "Nirsoft's AdvancedRun".
> 
> If improvements need to be made to generate the emu config, it would be better to define the problems with the current script and either open an issue or a PR to fix them. Honestly, I don't think I have any problem with it, but I was the one who made a similar script in the first place, which Mr. Goldberg modified and added to his repo.

Excuse me, but PowerShell was a brief mention in terms of running a script invisibly from a batch file. I've been specifically asking about and urging getting rid of the dependency of external tools. It makes me feel like you've only been skimming.

Considering you just complained about the lack of good communication, that feels hypocritical.

**Comment by alex47exe** [comment]
Trust me I've tested various methods trying to completely hide console when running various scripts or exe with parameters. The issue with your approach is the window (either powershell or cmd) will be visible for a fraction of second, and you can't compile bat or ps to exe without turning them into complete false positives nightmares. But if I'm missing anything here, maybe you could zip a complete example to have a look at it. Thanks.

**Comment by Edremon** [comment]
> Feel free to thoroughly test out generate_emu_config and create issues and fixes. You'll probably still be behind mine in terms of fixes, features, design and functionality after a few months. :)

I'm running it on all steam games that I want to play, if I had an issue with it, I would have sent a patch fixing it. What you are doing is just detrimental to the project and community. If you find problems, report them and even better if you have a proposed fix.

> As for the other nitpicking complaints, they're laughable... btw, python code, even compiled code still runs through an interpreter exe. Did you know that?

I'm a contributor to CPython, you didn't understand the meaning of my sentence.

> Excuse me, but PowerShell was a brief mention in terms of running a script invisibly from a batch file. I've been specifically asking about and urging getting rid of the dependency of external tools.

PowerShell and batch files are things that shouldn't be used directly as part of an in project script, those scripts should be usable on all operating system. This is part of those things that are in a wrong direction.

**Comment by alex47exe** [comment]
It's because you haven't tested it properly, as I said, you haven't been nitpicking into it the same way you nitpick into mine. :)

Obviously the way it generates the files now, they're only intended to be used on Windows. Once I completely refine the process to automate it for Windows, I will look into solutions to do exactly the same for Linux. Even though you can already create your own preset folder for Linux if you wish, and the tool will generate all required files, same as it does for Windows.

Tell that to countless devs that include bat, ps files in their repositories, if they're intended for Windows.

Bro, test the f thing with all its features, and say 'detrimental' again and try not to laugh at yourself!

**Comment by God-damnit-all** [comment]
> Trust me I've tested various methods trying to completely hide console when running various scripts or exe with parameters. The issue with your approach is the window (either powershell or cmd) will be visible for a fraction of second

I already responded to this here: https://github.com/Detanup01/gbe_fork/pull/2#issuecomment-2564825849

**Comment by God-damnit-all** [comment]
> PowerShell and batch files are things that shouldn't be used directly as part of an in project script, those scripts should be usable on all operating system. This is part of those things that are in a wrong direction.

Which is why I was asking why the external tools were needed...

**Comment by Edremon** [comment]
> It's because you haven't tested it properly, as I said, you haven't been nitpicking into it the same way you nitpick into mine. :)

If doing the same nitpick on it, everything check out for the current script: there are no binaries included, it runs on all platforms.

> Tell that to countless devs that include bat, ps files in their repositories, if they're intended for Windows.

That is extremely rare for an open source project, also for the longest while (under goldberg) that was a linux first project.

> Bro, test the f thing with all its features
 
Again what are missing features from the current implementation? From a quick glance, none of the features you included seems useful to me.

What the point of preset things when the whole design of this emulator is to use your user one? From goldberg readme: "I think that the way other steam emulators have an ini when you set everything on a per game setting is dumb. The only things that should be set on a per game setting is the things that are specific to that game like the appid, DLC, mods, interface versions, etc..."

I don't see the point of automatically finding an app id, that such a small task that add too much complexity when most of the times you already have that data (from downloading the game depot in the first place), again I'm not the current maintainer of this fork, but it was, I would reject that feature.

I have no need with downloading store page information of a game (like images/trailers), I personally believe that this is out of scope for this project, but it's already part of this project. No idea if it's currently broken but if it is, should be reported and either fixed or removed.

> and say 'detrimental' again and try not to laugh at yourself!

What I think is detrimental if you haven't understood is how you chose to contribute to this project and community, your time and knowledge about generating config would be better spent by reporting issues, and proposing patch rather than "forking".

**Comment by alex47exe** [comment]
This is comedy gold. I'm out. At this point you're just talking out of your a**, spewing out words you don't fully understand, without having the slightest idea what you're saying, since you don't know how mine works and what it adds, fixes or improves. You missed the whole idea around the purpose of my fixes and improvements for the tool. Haven't had the pleasure to interact with such a narrow minded individual in a long time, so thanks for that I guess! Feel free to fix/improve it or not on your fork! Have a good day!

**Comment by Detanup01** [comment]
I rarely using generate_emu_config and as I said before want to delete from here, old, unusable, and probably better to remake one from scratch.
When I crack any game that I own I just copy the full .ini file from the example and edit it.
That's it, I do not use any generation.
Locking this since generate emu will live in new repo, somewhen when I have time for steam bullshits.
Have fun, or whatever

Also feel free to swear. I dont fucking care.

**Pull request closed without merging**
