### PR TITLE
generate_emu_config: fixed steam auth 2fa and connection to tcp cm servers

### PR DESCRIPTION
**Pull request by Sak32009**
I just want to point out that the code needs improvement and i haven't fully tested it.

### CODE REVIEW

**Comment by alex47exe** [comment]
these lines:
```
else:
        webauth = WebAuth()
```
should be:
```
else:
        webauth = WebAuth(USERNAME, PASSWORD)
```
otherwise you get `TypeError: WebAuth.__init__() missing 1 required positional argument: 'username'` when running the uncompiled script

**Comment by Sak32009** [comment]
@alex47exe strange, did you recreate the venv before running the script?

**Comment by alex47exe** [comment]
Yes, I did. The compiled generate_emu_config doesn't have this issue.
As far as I see, it happened because the global python packages weren't yet updated with your new version of steam [client]
Fixed it by running this .bat script before generate_emu_config.py:
```
@echo off 
pip install -U git+https://github.com/Sak32009/steam_py_fork.git@fix-cm-servers
pip install pyinstaller 
pip install requests
pip install certifi
pip install configobj
```

**Comment by itsFaizan49** [comment]
@Sak32009  Can you share the compiled generate_emu_config package, i don't use github much so it will be greatly appreciated. idk why Detanup didn't merge this PR with the latest release. Anyways please do share the compiled generate emu config archive!

**Comment by Detanup01** [comment]
> @Sak32009 Can you share the compiled generate_emu_config package, i don't use github much so it will be greatly appreciated. idk why Detanup didn't merge this PR with the latest release. Anyways please do share the compiled generate emu config archive!

Because this:
https://github.com/Detanup01/gbe_fork/issues/58#issuecomment-2422558833
Moving out generate emu to 3rd party. Easier to update and currently even Steam has issues with itself!

**Comment by itsFaizan49** [comment]
@Detanup01 Oh nice, i will keep an eye out :)

**Comment by Sak32009** [comment]
Now everything seems fine even without this PR.
Closed.

**Comment by God-damnit-all** [comment]
In the latest gbe_fork I'm getting:
```
Unknown exception: HTTPSConnectionPool(host='api.steampowered.com', port=443): Max retries exceeded with url: /IAuthenticationService/GetPasswordRSAPublicKey/v1?account_name=IRemovedMyAccountNameFromThisException (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002D6B8E0BBF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')), maybe some account info is wrong?
Unexpected error:
name 'exit' is not defined
```
But yours is still working just fine.

**Comment by DogancanYr** [comment]
> In the latest gbe_fork I'm getting:
> 
> ```
> Unknown exception: HTTPSConnectionPool(host='api.steampowered.com', port=443): Max retries exceeded with url: /IAuthenticationService/GetPasswordRSAPublicKey/v1?account_name=IRemovedMyAccountNameFromThisException (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002D6B8E0BBF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')), maybe some account info is wrong?
> Unexpected error:
> name 'exit' is not defined
> ```
> 
> But yours is still working just fine.

Because this pull request was not merged because suddenly started to work normally.

**Comment by God-damnit-all** [comment]
> > In the latest gbe_fork I'm getting:
> > ```
> > Unknown exception: HTTPSConnectionPool(host='api.steampowered.com', port=443): Max retries exceeded with url: /IAuthenticationService/GetPasswordRSAPublicKey/v1?account_name=IRemovedMyAccountNameFromThisException (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002D6B8E0BBF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')), maybe some account info is wrong?
> > Unexpected error:
> > name 'exit' is not defined
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But yours is still working just fine.
> 
> Because this pull request was not merged because suddenly started to work normally.

And I'm saying it's not working "normally" for me on the latest version, but this PR patch still makes it work normally.

**Comment by God-damnit-all** [comment]
And it looks like Sak32009 deleted their steam_py_fork repo, so I can't do a new compile. Fuck.

**Comment by God-damnit-all** [comment]
It's now suddenly working even though I didn't change anything. I think whatever @Sak32009 altered in the steam_py fork made it work more consistently.

@Sak32009 What had been changed?

**Pull request closed without merging**
