### PR TITLE
Convert generate_interfaces from cpp to python

### PR DESCRIPTION
**Pull request by elyashivhazan**

### CODE REVIEW

**Comment by Detanup01** [comment]
I have to manually check for this. Thanks. 
And maybe need to edit the ymls to no longer need to compile interface generator

**Comment by Sak32009** [comment]
@Detanup01 but you still need to create executable with pyinstaller and in my opinion the advantages are zero.

**Comment by elyashivhazan** [comment]
btw why create it for migrate script and for this one, this 2 scripts are standalone with no deps

**Comment by Detanup01** [comment]
people gonna complain why not works

**Pull request closed without merging**
