### PR TITLE
trigger callback + call-result for failure in `SendQueryUGCRequest()`

### PR DESCRIPTION
**Pull request by otavepto**
my dumbass forgot to push this with #76 
solves #44

### CODE REVIEW

**Comment by universal963** [comment]
May I ask why flat api was changed in #76 ? I don't get it at the moment.

**Comment by otavepto** [comment]
Yes of course.
In order to support the 2 different structs I wanted to implement 2 functions, one dealing with SDK < 1.60, and another dealing with SDK >= 1.60.

The first problem is this:
Given one function having the same signature in 2 SDK versions `XX` and `YY`, and address actually since both are redirected to the same implementation, how can you detect the SDK version `XX` or `YY` ?
This is only possible by separating both functions and implementing each on its own, or at least both has to start as completely separate/independent functions and we can always converge them to the same implementation back if we wanted.

The header file of `ISteamUgc` in SDK < 1.60 and in SDK >= 1.60 look like this (indentical):
```c++
...
virtual bool GetQueryUGCResult( UGCQueryHandle_t handle, uint32 index, SteamUGCDetails_t *pDetails ) = 0;
...
virtual SteamAPICall_t RequestUGCDetails( PublishedFileId_t nPublishedFileID, uint32 unMaxAgeSeconds ) = 0;
...
```
And the assembly of the vftable (for each interface version) would contain the same addresses
```
...
&GetQueryUGCResult_implementation
...
&RequestUGCDetails_implementation
...
```
So what I did is retrospectively edit all older SDKs headers to add the function suffix `_old`, now SDKs < 1.60 look like this:
```
...
virtual bool GetQueryUGCResult_old( UGCQueryHandle_t handle, uint32 index, SteamUGCDetails_t *pDetails ) = 0;
...
virtual SteamAPICall_t RequestUGCDetails_old( PublishedFileId_t nPublishedFileID, uint32 unMaxAgeSeconds ) = 0;
...
```
While SDKs >= 1.60 look like this:
```
...
virtual bool GetQueryUGCResult( UGCQueryHandle_t handle, uint32 index, SteamUGCDetails_t *pDetails ) = 0;
...
virtual SteamAPICall_t RequestUGCDetails( PublishedFileId_t nPublishedFileID, uint32 unMaxAgeSeconds ) = 0;
...
```
That solves the first problem, because now in the .cpp file we can distinguish between 2 functions `GetQueryUGCResult` vs `GetQueryUGCResult_old`
Which also means each interface version has its own vftable now:
SDK < 1.60 (older table)
```
...
&GetQueryUGCResult_old_implementation
...
&RequestUGCDetails_old_implementation
...
```
SDK >= 1.60 (newer table)
```
...
&GetQueryUGCResult_implementation
...
&RequestUGCDetails_implementation
...
```
Great, but that immediately introduced another unwanted problem because of that different vftable, each instance would either contain the first table, or the second table, depending on the version of the interface, or more accurately, depending on how you `static_cast<..>(..)` the implementation class
https://github.com/Detanup01/gbe_fork/blob/7936cd6680ede0dc8b503789f7533f5e61996efe/dll/steam_client_interface_getter.cpp#L758-L764

If you static_cast the pointer to `ISteamUGC018 *` for example, you'll get the first (older) table, but if you static_cast to the latest version `static_cast<ISteamUGC *>(steam_ugc_temp)` you'll get the second (newer) table.

And now to answer your question, the 1st argument of the flat API is the class instance which you returned earlier, but at this point you don't know which interface version was this one, and you want the game to call the proper function either `GetQueryUGCResult` or `GetQueryUGCResult_old` (and it could be a client/player instance or a gameserver instance) so you have depend on the given pointer.

Goldberg was doing the vftable matching (to detect whether this address came from client/player instance or gameserver instance) using pointer mathematics and eventually ignoring it and forcefully calling either `get_steam_client()->steam_gameserver_ugc` or `get_steam_client()->steam_ug` which will give you back the instance you want but not with the correct vftable, previously that didn't matter since the target functions were the same, but now we have to call the proper one.

I have no idea why he/she was doing that, it's not even consistent, at other times the implementation was just a regular pointer dereference without any vftable matching like here:
https://github.com/Detanup01/gbe_fork/blob/7936cd6680ede0dc8b503789f7533f5e61996efe/dll/flat.cpp#L1497-L1505

**Comment by otavepto** [comment]
In case the above doesn't make it clearer, here's another perspective.
Let's say a game asked for the UGC interface to later call some function, this is how the assembly might look like
```asm
...
mov edx, 1 // hSteamUser
mov r8d, 1 // hSteamPipe
mov r9, &interface_name // "STEAMUGC_INTERFACE_VERSION017"
call GetISteamGenericInterface
...
mov rax. [rax] // now rax is the vftable address

...
call [rax + 8] // since each address is 8-bytes in 64-bit mode, this game is trying to call the second function of the interface
```
In the above example the game would call the second API function, and if we look at the header
https://github.com/Detanup01/gbe_fork/blob/7936cd6680ede0dc8b503789f7533f5e61996efe/sdk/steam/isteamugc017.h#L8-L18
It would be `CreateQueryAllUGCRequest()`

The trick here is the offset of the `rax` register:
* `[rax] or `[rax + 0]` is the first API function
* `[rax + 0x8]` is the 2nd API function
* `[rax + 0x10]` is the 3rd API function
* ...

But if you compare the newest SDK header with the older ones you'll see that for example `GetQueryUGCResult()` is the 6th function, which would be `[rax + 0x28]`.

What we want is some trick to make `[rax + 0x28]` point at our `function_xxx()` for newer SDK, but point at our `function_yyy()` for older SDK.
By renaming the function in older SDK headers, and providing a separate implementation for them, we've done that trick.

If we left the old code in the flat API as it was before
```c++
get_steam_client()->steam_ugc->GetQueryUGCResult()
```
We go back to square one, should the flat API call `GetQueryUGCResult_old()` or `GetQueryUGCResult()` ?
And more over, how do we know ?

**Comment by universal963** [comment]
Very interesting, thanks for the details. However one more thing to mention, from git history (https://gitlab.com/Mr_Goldberg/goldberg_emulator/-/commit/b189fbf2600ab1f246f6e2d354c116a60de8ecbc) we can see that Goldberg designed it somehow because of the crash that I personally have no ideas either, so maybe that is not totally pointless I guess?

**Comment by otavepto** [comment]
You are right, I just don't know what the original problem was nor do I know other workarounds, the original author(s) did not write any comments explaining the problem.
The safest option I can think of is always calling the old function
```c++
get_steam_client()->steam_ugc->GetQueryUGCResult_old()
```
I don't have any game which uses the flat API so I couldn't test it :/

**Comment by universal963** [comment]
According to my knowledge flat APIs are mostly used for non-C++ apps like C# ones, commonly used by games powered by Unity engine, though I currently don't know which game is suitable to test.

**Pull request merged**
